spring:
  kafka:
    user:
      bootstrap-servers: kafka:29029
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    cache:
      type: redis
      redis:
        host: localhost
        port: 6379

topic:
  user:user