spring:
  kafka:
    user:
      bootstrap-servers: kafka:29029
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

topic:
  user:user